# Site settings
title: Salient OS
description: An Arch based Linux Distribution for Creatives Everywhere :)
# baseurl: "/particle" # the subpath of your site, e.g. /blog
url: "https://salientos.github.io" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Salient OS
user_description: Salient OS is an arch-based rolling-release distribution aimed at creative multi-media / gaming enthusiasts.
user_title: Operating System
email: d3signr@gmail.com
#twitter_username: lorem_ipsum
github_username:  salientos
#gplus_username:  lorem_ipsum

# Google-analytics
#google-analytics:
#  id: ""

exclude: ['package.json', 'src' , 'node_modules']
